#ifndef  __TIMER_H__
#define  __TIMER_H__

enum {
    TIMER_SRC_LRC_CLK = 1,
    TIMER_SRC_RC_250k,
    TIMER_SRC_RC_16M,
    TIMER_SRC_STD_48M,
    TIMER_SRC_ICH_CLK,
    TIMER_SRC_CLKOUT2_CLK,
    TIMER_SRC_PAT_CLK,
    TIMER_SRC_TMRX_CIN = 15,
};

enum {
    TIMER_PRESCALE_1 = 0,
    TIMER_PRESCALE_4,
    TIMER_PRESCALE_16,
    TIMER_PRESCALE_64,
    TIMER_PRESCALE_2,
    TIMER_PRESCALE_8,
    TIMER_PRESCALE_32,
    TIMER_PRESCALE_128,
    TIMER_PRESCALE_256,
    TIMER_PRESCALE_1024,
    TIMER_PRESCALE_4096,
    TIMER_PRESCALE_16384,
    TIMER_PRESCALE_512,
    TIMER_PRESCALE_2048,
    TIMER_PRESCALE_8192,
    TIMER_PRESCALE_32768,
};


#endif  /*TIMER_H*/
